

version: '3.9'

services:

  db:
    image: mysql:8.0
    container_name: test_app_db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
        - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: test_app_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./app_data:/test_app/data
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER:  ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
    command: bash -c "/entrypoint.sh"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: test_app_frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
